### ISSUE TITLE
[TODO] quality control -> multiqc and fastqc 

### ISSUE THREAD

**Issue by fischer-hub** [fischer-hub/metagenomics#17]
- [ ] add `fastqc` to the pipeline
-  [ ] add `multiqc` to the pipeline
-  [ ] collect reports / summarys from fastqc, multiqc, bowtie2, paired-end merger
